# Generated by Django 3.2.5 on 2021-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('motDePasse', models.CharField(max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
