# Generated by Django 3.2.5 on 2021-07-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanagement',
            name='password2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
