# Generated by Django 3.1.1 on 2021-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountmanagement_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanagement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
