# Generated by Django 3.2.5 on 2021-08-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='multimedias')),
                ('file_type', models.CharField(max_length=255, null=True)),
                ('file_size', models.CharField(max_length=255, null=True)),
                ('file_kind', models.CharField(max_length=255, null=True)),
                ('file_post_author', models.CharField(max_length=255, null=True)),
                ('file_post_id', models.BigIntegerField()),
                ('file_path', models.CharField(max_length=255, null=True)),
                ('file_upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_duration', models.CharField(max_length=255, null=True)),
                ('file_origanal_name', models.CharField(max_length=255, null=True)),
                ('file_post_ua', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pmusik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_titre', models.CharField(max_length=255, null=True)),
                ('post_pays', models.CharField(max_length=255, null=True)),
                ('post_annee', models.DateField(max_length=255, null=True)),
                ('post_artiste', models.CharField(max_length=255, null=True)),
                ('post_description', models.CharField(max_length=255, null=True)),
                ('post_img', models.ImageField(null=True, upload_to='covers')),
                ('post_author', models.CharField(max_length=255, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_ua', models.CharField(max_length=255, null=True)),
                ('post_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category')),
            ],
        ),
        migrations.CreateModel(
            name='Pblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, null=True)),
                ('post_img', models.ImageField(null=True, upload_to='blog')),
                ('post_content', models.TextField(null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_author', models.CharField(max_length=255, null=True)),
                ('post_ua', models.CharField(max_length=255, null=True)),
                ('pub_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category')),
                ('pub_tags', models.ManyToManyField(null=True, to='forum.PubTags')),
            ],
        ),
    ]
