# Generated by Django 3.1.1 on 2021-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichiers',
            old_name='file_origanal_name',
            new_name='file_original_name',
        ),
        migrations.RemoveField(
            model_name='fichiers',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='fichiers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pblog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pmusik',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
