# Generated by Django 4.0.3 on 2022-03-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0002_auto_20210809_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pblog',
            name='post_img',
        ),
        migrations.RemoveField(
            model_name='pmusik',
            name='post_img',
        ),
        migrations.AlterField(
            model_name='fichiers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pblog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pmusik',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
