# Generated by Django 3.2.5 on 2021-08-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LesCommentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('comment_categorie', models.CharField(max_length=100, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.CharField(max_length=255, null=True)),
                ('comment_to', models.BigIntegerField(null=True)),
                ('comment_type', models.CharField(default='just comment', max_length=30)),
                ('comment_replyedTo', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
