# Generated by Django 4.0.3 on 2022-03-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210809_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lescommentaires',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
