# Generated by Django 3.2.5 on 2021-08-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeurs', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PubTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pub_author', models.CharField(max_length=255, null=True)),
                ('pub_categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category')),
                ('pub_tags', models.ManyToManyField(to='forum.PubTags')),
            ],
        ),
    ]
